omeusite/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('quizz/', include('quizz.urls')),
    path('admin/', admin.site.urls),
]

quizz/urls.py
from django.urls import path

from . import views

app_name = 'quizz'
urlpatterns = [
	path('',views.index,name='index'),
	path('<int:question_id>/',views.detail,name='detail'),
	path('<int:question_id>/results',views.results,name='results'),
	path('<int:question_id>/vote',views.vote,name='vote'),
]

quizz/models.py
from django.db import models
from django.utils import timezone

import datetime


# Create your models here.
class Question(models.Model):
	question_text = models.CharField(max_length=200)
	pub_date = models.DateTimeField('date published')

	def __str__(self):
		return self.question_text

	def was_published_recently(self):
		return self.pub_date >= timezone.now() - datetime.timedelta(days=1)

class Choice(models.Model):
	question = models.ForeignKey(Question, on_delete=models.CASCADE)
	choice_text = models.CharField(max_length=200)
	votes = models.IntegerField(default=0)

	def __str__(self):
		return self.choice_text

quizz/views.py
from django.shortcuts import render, get_object_or_404
from django.http import HttpResponse, Http404, HttpResponseRedirect
from .models import Question, Choice
from django.template import loader
from django.urls import reverse

# Create your views here.

def index(request):
	latest_question_list = Question.objects.order_by('-pub_date')[:5]
	template = loader.get_template('quizz/index.html')
	context = {'latest_question_list':latest_question_list
	}
	return HttpResponse(template.render(context, request))

def detail(request,question_id):
	try:
		question = Question.objects.get(pk=question_id)
	except Question.DoesNotExist:
		raise Http404('Question does not exist')
	return render(request, 'quizz/detail.html', {'question':question})

def results(request, question_id):
	question = get_object_or_404(Question, pk = question_id)
	return render(request, 'quizz/results.html', {'question': question})

def vote(request, question_id):
	question = get_object_or_404(Question, pk=question_id)
	try:
		selected_choice = question.choice_set.get(pk=request.POST['choice'])
	except (KeyError, Choice.DoesNotExist):
		#redisplay question form.
		return render(request, 'quizz/detail.html', {'question': question,' error_message': "You didn't select a choice."})
	else:
		selected_choice.votes += 1
		selected_choice.save()
		return HttpResponseRedirect(reverse('quizz:results', args=(question.id,)))

quizz/templates/quizz/detail.html
<DOCTYPE !html>
	<html>
		<head>
		</head>
			<body style="background-color:black">
			<form action="{% url 'quizz:vote' question.id %}" method="post">
			{% csrf_token  %}
			<h1 style="text-align:center;color:yellow">Quizz show!</h1>
			<h3 style="color:yellow;text-align:center">Quizz number {{ question.id }}</h3>
			<fieldset>
			<legend style="color:yellow"><h1 style="color:yellow">{{question.question_text}}</h1></legend>
			{% if error_message %} <p><strong> {{error_message}}</strong></p>{% endif %}
			{% for choice in question.choice_set.all %}
				<input style="color:yellow" type="radio" name="choice" id="choice{{forloop.counter}}" value="{{choice.id}}">
				<label style="color:yellow" for="choice{{forloop.counter}}">{{choice.choice_text}}</label><br>
			{% endfor %}
			</fieldset>
			<br>
			<input style="display:block;margin:auto" type="submit" value="Vote"><br>
			<button style="display:block;margin:auto;"><a href="{% url 'quizz:index' %}" style="text-decoration:none;">Go Back</a></button>
			</form>
			<body>
	</html>   

quizz/templates/quizz/index.html
<!DOCTYPE html>
<html>
	<head>
		<meta charset='utf-8'>
		<title>My test page</title>
	</head>
	<body style="background-color:pink">
		<h1 style="text-align:center;">The quizz Show!</h1>
		<p>The quizz questions list:</p>
		{% if latest_question_list %}
		<ul>
		{% for question in latest_question_list %}
		<li><a href="{% url 'quizz:detail' question.id %}">{{question.question_text}}</a></li>
		{% endfor %}
		</ul>
		{% else %}
		<p> No quizz are available.</p>
		{% endif %}
	</body>
</html>

quizz/templates/quizz/results.html
<DOCTYPE !html>

<html>
	<head>

	</head>

	<body style="background-color:black; color:yellow; text-align:center">
		<h1>Results</h1>
		{{question.question_text}}

		<ul style="color:yellow; margin-left:25%;margin-right:25%;">
		{% for choice in question.choice_set.all %}
			<li>{{choice.choice_text}} -- {{ choice.votes }} vote{{ choice.votes|pluralize }}</li>
		{% endfor %}
		</ul>

		<a href="{% url 'quizz:detail' question.id %}"> Vote Again ?</a>
	</body>
</html>